CREATE TABLE IF NOT EXISTS utilisateur (
    ID_UTILISATEUR INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255) NOT NULL,
    PRENOM VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    MOT_DE_PASSE VARCHAR(255) NOT NULL,
);