name: CI

on:
  push:
    branches:
      - main  # Déclenche les tests sur la branche main
  pull_request:
    branches:
      - main  # Déclenche les tests sur les pull requests vers la branche main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &  # Démarre le serveur en arrière-plan

      - name: Run tests
        run: npm test